import java.text.DecimalFormat;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Francisco A. Reyes
 */
public class GastoGasolina extends javax.swing.JFrame {

    
    public GastoGasolina() {
                                 
        initComponents();
        texto1.setText("");
        texto2.setText("€");
        texto3.setText("€");
        texto4.setText("horas:min");
        texto5.setText("");
        chistaco.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiq1 = new javax.swing.JLabel();
        etiq2 = new javax.swing.JLabel();
        etiq3 = new javax.swing.JLabel();
        etiq4 = new javax.swing.JLabel();
        texto1 = new javax.swing.JTextField();
        texto2 = new javax.swing.JTextField();
        texto3 = new javax.swing.JTextField();
        texto4 = new javax.swing.JTextField();
        texto4_2 = new javax.swing.JTextField();
        botonCalcula = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto5 = new javax.swing.JTextArea();
        chistaco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiq1.setText("Total Kms:");

        etiq2.setText("Precio Combustible:");

        etiq3.setText("Coste Viaje:");

        etiq4.setText("Duración Viaje: HH:mm");

        texto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto1MouseClicked(evt);
            }
        });

        texto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto2MouseClicked(evt);
            }
        });
        texto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto2ActionPerformed(evt);
            }
        });

        texto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto3MouseClicked(evt);
            }
        });

        texto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto4MouseClicked(evt);
            }
        });

        texto4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto4_2ActionPerformed(evt);
            }
        });

        botonCalcula.setText("Calcular Consumo");
        botonCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculaActionPerformed(evt);
            }
        });

        texto5.setEditable(false);
        texto5.setBackground(new java.awt.Color(204, 204, 204));
        texto5.setColumns(20);
        texto5.setRows(5);
        jScrollPane1.setViewportView(texto5);

        chistaco.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCalcula)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texto1)
                            .addComponent(etiq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chistaco, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(texto2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiq3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiq4)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texto4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq1)
                    .addComponent(etiq2)
                    .addComponent(etiq3)
                    .addComponent(etiq4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chistaco)
                .addGap(24, 24, 24)
                .addComponent(botonCalcula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculaActionPerformed
        double kmTotal = Double.valueOf(texto1.getText());
        double precioActual = Double.valueOf(texto2.getText());
        double costeViaje = Double.valueOf(texto3.getText());
        
        double litrosUsados = costeViaje / precioActual;
        double consumoXKm = ((litrosUsados*1)/kmTotal);       
        double consumoX100km = ((litrosUsados*100) / kmTotal);
        
        DecimalFormat formatoDecimal = new DecimalFormat ("###.##");
        String consumo1 = formatoDecimal.format(consumoXKm);
        String consumo100 = formatoDecimal.format(consumoX100km);
        String eurosKm = String.valueOf(formatoDecimal.format(consumoXKm * precioActual));
        String euros100Km = String.valueOf(formatoDecimal.format(consumoX100km * precioActual));
        
        //Velocidad Media KM/h M/s
        
        double horas = Double.valueOf(texto4.getText());
        double minutos = Double.valueOf(texto4_2.getText());
        double vMediaKm = kmTotal / horas + (minutos / 60);
        String vMediaMS = formatoDecimal.format((kmTotal * 1000) / ((horas * 3600) + (minutos * 60)));
                
        texto5.setText("Litros X Km: " + consumo1 + "L // Gasto x Km: " + eurosKm + " €"); 
        texto5.append("\nLitros x 100Km: " + consumo100 + "L // Gasto x 100 Km: " + euros100Km + " €");
        texto5.append("\nVelocidad Media(KM/H): " + vMediaKm + " km/h // (M/S): " + vMediaMS + " m/s");
        
        String chiste = (precioActual > 1.40) ? "Vaya Clavada, chaval" : "Has comprao en galp, eh bribón?";
        chistaco.setText(chiste);
        String pisaHuevers = (vMediaKm < 80.0) ? "Vas pisando huevers¡¡¡ Achucha ahí¡¡" : "";
        texto5.append("\n\n" + pisaHuevers);
        
    }//GEN-LAST:event_botonCalculaActionPerformed

    private void texto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto3MouseClicked
         texto3.setText(null); // TODO add your handling code here:
       
    }//GEN-LAST:event_texto3MouseClicked

    private void texto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto2ActionPerformed

    private void texto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto2MouseClicked
        texto2.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_texto2MouseClicked

    private void texto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto1MouseClicked
        texto1.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_texto1MouseClicked

    private void texto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto4MouseClicked
        texto4.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_texto4MouseClicked

    private void texto4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto4_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GastoGasolina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GastoGasolina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GastoGasolina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GastoGasolina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GastoGasolina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcula;
    private javax.swing.JLabel chistaco;
    private javax.swing.JLabel etiq1;
    private javax.swing.JLabel etiq2;
    private javax.swing.JLabel etiq3;
    private javax.swing.JLabel etiq4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField texto1;
    private javax.swing.JTextField texto2;
    private javax.swing.JTextField texto3;
    private javax.swing.JTextField texto4;
    private javax.swing.JTextField texto4_2;
    private javax.swing.JTextArea texto5;
    // End of variables declaration//GEN-END:variables
}
